name: sync kubrenetes images

on:
  workflow_dispatch: # 手动触发
  schedule:
  - cron: 0 */2 * * *

jobs:
  sync-k8s-image:
    name: sync kubrenetes images
    runs-on: ubuntu-latest
    steps:
    - name: sync
      uses: alterem/sync-k8s-images/action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # kubernetes_version: ${{ secrets.KUBERNETES_VERSION }}
        repository: v5cn
